### ISSUE TITLE
Unable to create tables in database. (PostalService 1.0.7)

### ISSUE THREAD

**Issue by South-Paw** [ebiggz/PostalService#2]
Hi there,

Trying to use your plugin but the following error persists. I enabled debug mode to get this trace for you to do something about it.

```java
[23:24:15] [Server thread/INFO]: [PostalService] Enabling PostalService v1.0.7
[23:24:15] [Server thread/INFO]: [PostalService] Hooked into Vault!
[23:24:16] [Server thread/ERROR]: [PostalService] Unable to create tables in database, plugin may not function as intended!
[23:24:16] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes
[23:24:16] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:24:16] [Server thread/WARN]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[23:24:16] [Server thread/WARN]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[23:24:16] [Server thread/WARN]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[23:24:16] [Server thread/WARN]: 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
[23:24:16] [Server thread/WARN]: 	at com.mysql.jdbc.Util.getInstance(Util.java:387)
[23:24:16] [Server thread/WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:942)
[23:24:16] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3966)
[23:24:16] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3902)
[23:24:16] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2526)
[23:24:16] [Server thread/WARN]: 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2673)
[23:24:16] [Server thread/WARN]: 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)
[23:24:16] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdateInternal(StatementImpl.java:1540)
[23:24:16] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeLargeUpdate(StatementImpl.java:2595)
[23:24:16] [Server thread/WARN]: 	at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1468)
[23:24:16] [Server thread/WARN]: 	at com.ebiggz.postalservice.backend.database.Database.createTable(Database.java:77)
[23:24:16] [Server thread/WARN]: 	at com.ebiggz.postalservice.backend.database.Database.createTables(Database.java:61)
[23:24:16] [Server thread/WARN]: 	at com.ebiggz.postalservice.backend.database.Database.checkConnection(Database.java:51)
[23:24:16] [Server thread/WARN]: 	at com.ebiggz.postalservice.PostalService.loadDatabase(PostalService.java:249)
[23:24:16] [Server thread/WARN]: 	at com.ebiggz.postalservice.PostalService.onEnable(PostalService.java:154)
[23:24:16] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271)
[23:24:16] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[23:24:16] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[23:24:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:375)
[23:24:16] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:325)
[23:24:16] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.t(MinecraftServer.java:419)
[23:24:16] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.l(MinecraftServer.java:380)
[23:24:16] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.a(MinecraftServer.java:335)
[23:24:16] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:272)
[23:24:16] [Server thread/WARN]: 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542)
[23:24:16] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[23:24:16] [Server thread/INFO]: [PostalService] Sucessfully connected to the database!
[23:24:16] [Server thread/WARN]: [PostalService] UUIDs are enabled but the server is running in Offline Mode. UUIDs have been disabled. To force the use of UUIDs while in Offline mode, set "use-uuids" to "always" in the config.
[23:24:16] [Server thread/INFO]: [PostalService] Enabled!
```

Thanks looking forward to using the plugin.

**Comment by steffen678** [comment]
Don't use utf8 as charset but latin1 or something. It's going to work then.
