### ISSUE TITLE
Broken with Spigot 1.12

### ISSUE THREAD

**Issue by k-jiang** [ebiggz/PostalService#3]
Tested with:
PostalService 1.0.7
Spigot 1.12 build 1304

It seems that spigot 1.12 has delete some api. According to the thread you may need to reconfigure the build scripts and re-build it with the new version. [Link to the thread is here](https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-12-pre6-released.240317/).

Some other plugins has the same issue as well (https://github.com/wargamer/SignShop/issues/40). They said it is due to `configuration.file.FileConfiguration.load` being removed.

Exception while loading:
```
[01:35:39] [Server thread/INFO]: [PostalService] Enabling PostalService v1.0.7
[01:35:39] [Server thread/INFO]: [PostalService] Hooked into Vault!
[01:35:39] [Server thread/ERROR]: Error occurred while enabling PostalService v1.0.7 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(Ljava/io/InputStream;)Lorg/bukkit/configuration/file/YamlConfiguration;
	at com.ebiggz.postalservice.config.ConfigAccessor.reloadConfig(ConfigAccessor.java:36) ~[?:?]
	at com.ebiggz.postalservice.config.ConfigAccessor.getConfig(ConfigAccessor.java:49) ~[?:?]
	at com.ebiggz.postalservice.utils.UUIDUtils.loadFile(UUIDUtils.java:104) ~[?:?]
	at com.ebiggz.postalservice.PostalService.onEnable(PostalService.java:115) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.12.jar:git-Spigot-d5dfb24-ed8c725]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

P.S the plugin has no issue with 1.11.2 and below.

Thank you for your effort!

**Comment by k-jiang** [comment]
I have fix it my self. Go check the pull request :)
